### ISSUE TITLE
Configure global context for translations

### ISSUE THREAD

**Issue by dansimau** [dmitry-zaitsev/mooi#59]
It would be ideal if the configuration file could accept some kind of free form text to add context to every translation. This could improve the quality of translations by disambiguating common words or phrase used throughout the product.

---

For example, imagine we are working on an app that deals with truckload shipments. We refer these as "loads". Given the following UI label:

* value: "Add load"
* description: "Button for allowing customer to add a load"

(Note that I deliberately wrote an ambiguous description, because this is commonly what I see people doing.)

Given on this text and description, as a translator, how do you know whether "load" refers to a cargo shipment, or an electrical current?

---

I would propose that there is a field in the config file where you can write free form context about the translations that will be passed to the LLM as-is.

For example, we could write:

```
context: |
  We are translating strings for display in the UI of a mobile app. The app
  allows truck drivers to claim and track cargo shipments (which we commonly
  refer to as "loads").
```

Now even with a poor description, we can hint to the LLM that load refers to a cargo load, not an electrical current.

The hypothesis here is that the quality of translations will improve because the app now has more context about what the strings are (and this doesn't have to be repeated over and over in the descriptions).

**Comment by dmitry-zaitsev** [comment]
This is supported now ✅ 

Add these to global config.yaml

```yaml
context: |
  All translated phrases should start with Yare, yare...

useContextForChecksum: true # (Optional, false by default) - whether the global context should be taken into account when we detect whether a value needs to be re-translated
```
